In [5]:
from numpy import *

In [12]:
v = array([1,2,3])
sqrt(2*v)
#print(sqrt(2*v))
sqrt([1,4,9])

array([ 1.,  2.,  3.])

In [16]:
v_float = array([1,2], dtype='f')
type(v_float[0])

numpy.float32

In [14]:
type(v[0])

numpy.int64

In [18]:
v = array([1,2,3.0])
type(v[0])

numpy.float64

In [21]:
v=array(['1','2',4])
type(v[0])

numpy.str_

In [25]:
print(sqrt(int(v)))

TypeError: only length-1 arrays can be converted to Python scalars

In [28]:
A = array( [
    [1,2,-1],
    [3,4,-1]] )
print(A)

[[ 1  2 -1]
 [ 3  4 -1]]


In [32]:
A.transpose()

array([[ 1,  3],
       [ 2,  4],
       [-1, -1]])

In [37]:
print("Número de filas: ", A.shape[0])
A.shape

Número de filas:  2


(2, 3)

In [38]:
v=array([1,2,3])
print("Número de elementos", v.shape[0])

Número de elementos 3


In [43]:
size(A)

6

In [45]:
array(list(range(6)))

array([0, 1, 2, 3, 4, 5])

In [46]:
arange(6)

array([0, 1, 2, 3, 4, 5])

In [51]:
primero=0
último=2
n_elementos = 5
space(primero, último, n_elementos)

array([   1.        ,    3.16227766,   10.        ,   31.6227766 ,  100.        ])

In [60]:
a=3
b=10
n=6
dx = (b-a)/n

# 1) Creamos un array de tamaño n+1
x_i = zeros(n+1)
print("Array de ceros:", x_i)

for i in range(n+1): # 0, 1, ..., n
   x_i[i] = a + dx*i

set_printoptions(precision=3)
print(f"Array final:{x_i}")

Array de ceros: [ 0.  0.  0.  0.  0.  0.  0.]
Array final:[  3.      4.167   5.333   6.5     7.667   8.833  10.   ]


In [64]:
random.rand(2,5)

array([[ 0.759,  0.744,  0.448,  0.67 ,  0.032],
       [ 0.682,  0.073,  0.38 ,  0.416,  0.432]])

In [69]:
# Otra posibilidad
from numpy.random import rand
2+3*rand(3,2) # Números aleatorios en [2, 5)

array([[ 2.826,  4.575],
       [ 3.372,  2.933],
       [ 3.954,  2.861]])

In [70]:
help(rand)

Help on built-in function rand:

rand(...) method of mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]

In [75]:
x = arange(11)

comienzo=0
fin=size(x)-1
incremento=2
x[comienzo:fin:incremento] # Arrays con índice par

array([0, 2, 4, 6, 8])

In [78]:
v=arange(1,21)
print("v =",v)

u = v[::2]
print("u =", u)

w = v[1::2]
print("w =", w)

print("u+w = ", u+w)

v = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
u = [ 1  3  5  7  9 11 13 15 17 19]
w = [ 2  4  6  8 10 12 14 16 18 20]
u+w =  [ 3  7 11 15 19 23 27 31 35 39]


In [82]:
v = arange(1,21)
print("v =",v)

print("Suma de pares e impares:")
print(v[::2] + v[1::2])

v = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Suma de pares e impares:
[ 3  7 11 15 19 23 27 31 35 39]


In [83]:
!ls

1-Shell_Unix.ipynb		 img	       Makefile
2-Python_Language.ipynb		 Inicio.html   Untitled.ipynb
3-Bibliotecas_Matematicas.ipynb  Inicio.ipynb


In [87]:
# Importamos otro paquete para funciones relacionadas con el sistema
# operativo
import os
os.listdir()

['Inicio.ipynb',
 '1-Shell_Unix.ipynb',
 'Inicio.html',
 '3-Bibliotecas_Matematicas.ipynb',
 '2-Python_Language.ipynb',
 'Untitled.ipynb',
 '.ipynb_checkpoints',
 'Makefile',
 'img']

In [95]:
from scipy.linalg import solve
A=diag([1,2,3,4])
print("A =")
print(A)
b=ones(4)
print("b =",b)

A =
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
b = [ 1.  1.  1.  1.]


In [93]:
solve(A,b)

array([ 1.   ,  0.5  ,  0.333,  0.25 ])